name: CI/CD for Flask App

on:
  push:
    branches:
      - master  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and Push Docker Image
      run: |
        docker build -t athifal/flask-app:latest .
        docker push athifal/flask-app:latest

    - name: Set up SSH
      run: |
        echo "${{ secrets.EC2_PEM_KEY }}" > ec2-key.pem
        chmod 600 ec2-key.pem

    - name: Deploy on EC2
      run: |
        ssh -i ec2-key.pem -o StrictHostKeyChecking=no ec2-user@44.203.87.46 << 'EOF'
        docker pull athifal/flask-app:latest
        docker stop flask-app || true
        docker rm flask-app || true
        docker run -d --name flask-app -p 80:5000 athifal/flask-app:latest
        EOF
