name: CI/CD for Flask App

on:
  push:
    branches:
      - master  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        echo "${{ secrets.EC2_PEM_KEY }}" > ec2-key.pem
        chmod 600 ec2-key.pem

    - name: Copy Files to EC2
      run: |
        ssh -i ec2-key.pem -o StrictHostKeyChecking=no ec2-user@44.203.87.46 "mkdir -p ~/flask-app"
        scp -i ec2-key.pem -o StrictHostKeyChecking=no -r * ec2-user@44.203.87.46:~/flask-app/

    - name: Deploy on EC2
      run: |
        ssh -i ec2-key.pem -o StrictHostKeyChecking=no ec2-user@44.203.87.46 << 'EOF'
        cd ~/flask-app
        docker stop flask-app || true
        docker rm flask-app || true
        docker build -t flask-app .
        docker run -d --name flask-app -p 80:5000 flask-app
        EOF
